// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6LPgtCnpmmDP5or3x8TFoM_ds2tO_iO4',
    appId: '1:179389055197:web:cdb48d7d905585963cdb34',
    messagingSenderId: '179389055197',
    projectId: 'filesphere-731f1',
    authDomain: 'filesphere-731f1.firebaseapp.com',
    storageBucket: 'filesphere-731f1.appspot.com',
    measurementId: 'G-5V8QGJ6F8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31Jp-CLdfbrz3QoFpLHl2_u0IcAnrOHo',
    appId: '1:179389055197:android:b891213b3eb32a0b3cdb34',
    messagingSenderId: '179389055197',
    projectId: 'filesphere-731f1',
    storageBucket: 'filesphere-731f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKc_FPhO0SlgVE3SkH6NFACFME44aguoc',
    appId: '1:179389055197:ios:6a64cb016e1201903cdb34',
    messagingSenderId: '179389055197',
    projectId: 'filesphere-731f1',
    storageBucket: 'filesphere-731f1.firebasestorage.app',
    iosBundleId: 'com.example.filesphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxcpvxTHdZ47QbfoqtSXuweJK_MFCxKwI',
    appId: '1:268283662507:ios:398d70dc696eb9b16de7ee',
    messagingSenderId: '268283662507',
    projectId: 'flutterloginapp-b8dcd',
    storageBucket: 'flutterloginapp-b8dcd.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xwB_VIeU7PszO-7jMQ1JlyLlbpHBCfg',
    appId: '1:268283662507:web:853f13e7c016d81a6de7ee',
    messagingSenderId: '268283662507',
    projectId: 'flutterloginapp-b8dcd',
    authDomain: 'flutterloginapp-b8dcd.firebaseapp.com',
    storageBucket: 'flutterloginapp-b8dcd.firebasestorage.app',
    measurementId: 'G-Y1LDXZ6FP8',
  );
}
